const data = new Date();
console.log(data);
console.log(typeof(data));
console.log(data.toString());
console.log(data.toUTCString());
console.log(data.valueOf());
console.log(data.getFullYear());
console.log(data.getMonth());
console.log(data.getDate());
console.log(data.getHours());
console.log(data.getMinutes());
console.log(data.getSeconds());
console.log(data.getMilliseconds());
console.log(data.getDay());
console.log(data.getTime());